<?php
// $Id$

/**
 * @file
 * An example module to redirect the path from a node view for at
 * specific type to a view.
 */
 
/**
 * Implementation of hook_init().
 */
function hippel_redirect_init() {
  // Using arg() instead of menu_get_item(). Rumor has it menu_get_item
  // can occassionally cause WSOD.
  // We make sure arg(2) is empty so we do not redirect on edit or other
  // node sub pages.
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == '') {
    $node = node_load(arg(1));
    if ($node->type == 'reply') {
      drupal_goto('discuss/'. $node->field_reply_refto_discuss[0]['nid']);
    }
    elseif ($node->type == 'discuss') {
      drupal_goto('discuss/'. $node->nid);
    }
  }
}
